SELECT DATE(t1.DtCriacao) AS dtRef,
        t2.IdProduto,
        CASE
            WHEN t2.IdProduto = '1' THEN 'Airflow Lover'
            WHEN t2.IdProduto = '2' THEN 'Comida'
            WHEN t2.IdProduto = '3' THEN 'Comida'
            WHEN t2.IdProduto = '4' THEN 'Comida'
            WHEN t2.IdProduto = '5' THEN 'ChatMessage'
            WHEN t2.IdProduto = '6' THEN 'Churn_10pp'
            WHEN t2.IdProduto = '7' THEN 'Churn_2pp'
            WHEN t2.IdProduto = '8' THEN 'Churn_5pp'
            WHEN t2.IdProduto = '9' THEN 'Comida'
            WHEN t2.IdProduto = '10' THEN 'Daily Loot'
            WHEN t2.IdProduto = '11' THEN 'Lista de presença'
            WHEN t2.IdProduto = '12' THEN 'Presença Streak'
            WHEN t2.IdProduto = '13' THEN 'R Lover'
            WHEN t2.IdProduto = '14' THEN 'Reembolso: Troca de Pontos StreamElements'
            WHEN t2.IdProduto = '15' THEN 'Resgatar Ponei'
            WHEN t2.IdProduto = '16' THEN 'Comida'
            WHEN t2.IdProduto = '17' THEN 'Troca de Pontos StreamElements'
            WHEN t2.IdProduto = '18' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '19' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '20' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '21' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '22' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '23' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '24' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '25' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '26' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '27' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '28' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '29' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '30' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '31' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '32' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '33' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '34' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '35' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '36' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '37' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '38' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '39' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '40' THEN 'Venda Item RPG'
            WHEN t2.IdProduto = '41' THEN 'join failed'
            WHEN t2.IdProduto = '001 - Espada Longa' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '002 - Espada Curta' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '003 - Armadura de Couro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '004 - Armadura de Placas' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '005 - Botas de Agilidade' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '006 - Botas de Força' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '007 - Cajado de Fogo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '008 - Cajado de Gelo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '009 - Chapéu do Mago' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '010 - Chapéu do Sábio' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '011 - Espada Bastarda' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '012 - Armadura de Escamas' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '013 - Botas Silenciosas' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '014 - Cajado da Vida' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '015 - Chapéu do Ladino' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '016 - Espada Curvada' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '017 - Armadura Mística' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '018 - Botas do Vento' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '019 - Cajado do Trovão' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '020 - Chapéu do Guerreiro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '021 - Espada Flamejante' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '022 - Armadura de Sombras' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '023 - Botas de Velocidade' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '024 - Cajado da Terra' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '025 - Espada do Caos' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '026 - Armadura de Luz' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '027 - Botas de Ferro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '028 - Cajado do Vento' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '029 - Espada de Gelo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '030 - Armadura de Fogo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '031 - Botas de Ouro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '032 - Cajado do Sol' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '033 - Espada do Dragão' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '034 - Armadura de Cristal' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '035 - Botas de Furtividade' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '036 - Cajado do Eclipse' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '037 - Chapéu do Guardião' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '038 - Espada do Vento' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '039 - Armadura de Ferro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '040 - Botas de Cristal' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '041 - Cajado do Inferno' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '042 - Chapéu do Arqueiro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '043 - Espada de Luz' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '044 - Armadura de Ouro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '045 - Botas de Lava' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '046 - Cajado do Tempo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '047 - Chapéu do Feiticeiro' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '048 - Espada do Caçador' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '049 - Armadura de Dragão' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '050 - Botas de Veludo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '051 - Cajado do Céu' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '052 - Chapéu do Mestre' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '053 - Espada de Prata' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '054 - Armadura de Diamante' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '055 - Botas de Energia' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '056 - Cajado do Universo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '057 - Chapéu do Alto Guardião' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '058 - Espada do Apocalipse' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '059 - Armadura Celestial' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '060 - Botas do Relâmpago' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '061 - Cajado do Caos' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '062 - Chapéu do Arcanjo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '063 - Espada do Infinito' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '064 - Armadura do Dragão Ancião' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '065 - Botas do Vácuo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '066 - Cajado do Cosmos' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '067 - Chapéu do Guardião Supremo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '068 - Adaga Sombria' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '069 - Adaga de Prata' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '070 - Adaga do Caçador' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '071 - Adaga Flamejante' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '072 - Adaga do Vento' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '073 - Adaga de Gelo' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '074 - Adaga do Eclipse' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '075 - Adaga do Relâmpago' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '076 - Adaga do Cosmos' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = '077 - Adaga do Apocalipse' THEN 'Compra Item RPG'
            WHEN t2.IdProduto = 'fiel-score-0.1' THEN 'Fiel Score < 0.1'
            WHEN t2.IdProduto = 'fiel-score-0.25' THEN 'Fiel Score < 0.25'
            WHEN t2.IdProduto = 'fiel-score-0.5' THEN 'Fiel Score < 0.5'
            WHEN t2.IdProduto = 'fiel-score-0.75' THEN 'Fiel Score < 0.75'
            WHEN t2.IdProduto = 'fiel-score-1' THEN 'Fiel Score <= 1'
            ELSE t2.IdProduto
       END AS descNomeProduto,
       COUNT(distinct t1.IdTransacao) AS nrQuantidadeTransacoes,
       COUNT(distinct t1.IdCliente) AS nrQuantidadeClientes,
       SUM(t1.QtdePontos) AS nrQuantidadePontos,
       SUM(CASE WHEN t1.QtdePontos > 0 THEN t1.QtdePontos ELSE 0 END) AS nrQuantidadePontosPos,
       SUM(CASE WHEN t1.QtdePontos < 0 THEN t1.QtdePontos ELSE 0 END) AS nrQuantidadePontosNeg

FROM silver.upsell.transacoes AS t1

LEFT JOIN silver.upsell.transacao_produto AS t2
ON t1.IdTransacao = t2.IdTransacao

WHERE DATE(t1.DtCriacao) = '{dt_ref}'

GROUP BY DATE(t1.DtCriacao), t2.IdProduto 
GROUPING SETS ((DATE(t1.DtCriacao), t2.IdProduto), (DATE(t1.DtCriacao)))
ORDER BY dtref